name: Verify

on:
  # Trigger the workflow on push or pull request on master branch
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Build & test linux/amd64 image
      run: make images test

    - name: Build multi-arch images and binaries
      run: make multiarch-tar

